### ISSUE TITLE
Non-focused tests still run under rake and bundle exec

### ISSUE THREAD

**Issue by joshweinstein** [seattlerb/minitest-focus#1]
Hi, thanks for your great work Ryan! Eager to use minitest-focus, but haven't been able to get it working in a project using `bundle exec`. Running minitest-focus' tests locally, I notice that when executing `ruby -Ispec test/minitest/test_focus.rb`, only the focused tests are run and both pass. However, when executing `rake`, both focused and non-focused tests run (using rvm, ruby 1.9.3-p327, and minitest 4.6.2). 

Am I missing something or is minitest-focus not designed to work when tests are run via `rake` or `bundle exec`?

**Comment by zenspider** [comment]
Sorry. this slipped through the cracks. 

The way that minitest-focus works is by injecting the class using it w/ a `method_added` hook. That hook manipulates ARGV in such a way that minitest can then process and filter with. The problem is the way that rake's test task works is hostile to ARGV. Add `p ARGV` at the end of your focused file and you should see the right stuff, but it won't trigger the filter correctly.

If you want a quick experiment, steal `make_test_cmd` from my hoe gem and use that to create a new task that runs your stuff.

What I really should do is take `Rake::TestTask`, fix it, and ship it with minitest.

**Comment by zenspider** [comment]
No response. Closing. Please reopen if you think it should be.
