### ISSUE TITLE
Fails to install with MediumSecurity

### ISSUE THREAD

**Issue by svoop** [seattlerb/minitest-focus#15]
Here's the message `bundle install` prints:

```
The gem minitest-focus-1.1.2 can't be installed because the security policy
didn't allow it, with the message: no digests provided (probable bug)
```

**Comment by zenspider** [comment]
I don't know what that means. :shrug:

**Comment by svoop** [comment]
Oh, lost track of this, sorry! Here's the full output:

```
The gem minitest-focus-1.2.1 can't be installed because the security policy
didn't allow it, with the message: certificate
/CN=ryand-ruby/DC=zenspider/DC=com not valid after 2020-12-12 00:02:04 UTC
```

When Bundler is configured with `bundle config --trust-policy MediumSecurity`, the gem cannot be installed by Bundler and raises the above error. Apparently, the key/cert mentioned in the gemspec with `spec.cert_chain` and `spec.signing_key` has expired.

As a side note: You might want to watch [this issue on Bundler](https://github.com/rubygems/rubygems/issues/3386) which might lead to a first step to standardize the creation of certs.

**Comment by zenspider** [comment]
Yeah... it expires all the time. The real problem is that while I can manually create a key with an expiry of 10 years, rubygems doesn't respect that value and when in auto-regenerates a key, it does it for only 1 year. So this keeps coming back year after year.

In short, rubygems has never really made security a real priority and until it does, it is going to be a PITA to both authors and users. I'm not really wanting to re-release all my gems every year so that a dozen of you can run with `MediumSecurity` (really... you're very few and far between... i mean no offense). I'd MUCH rather generate a key for 5-10 years and have it regenerate for the same value when it needs to... but that bug was filed a looong time ago and ignored.

I'm NOT a security wonk. If there is a better way around this, please advise.

**Comment by svoop** [comment]
@zenspider I agree 100%, the current workflows are broken for everybody. There are paths out of this deadlock such as [TUF (adopted by Python, Docker)](https://github.com/rubygems/rubygems.org/pull/626), but it's non-trivial and got stuck in Rubyland.

**Comment by zenspider** [comment]
I just did a release... so it's fixed for a year. Closing.
